# Generated by Django 5.2.5 on 2025-08-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='dashboard.permission', verbose_name='权限'),
        ),
    ]
