# Generated by Django 5.2.5 on 2025-08-29 02:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiWhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='url地址', max_length=200, verbose_name='url')),
                ('method', models.IntegerField(blank=True, default=0, help_text='接口请求方法', null=True, verbose_name='接口请求方法')),
                ('enable_datasource', models.BooleanField(blank=True, default=True, help_text='激活数据权限', verbose_name='激活数据权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '接口白名单',
                'verbose_name_plural': '接口白名单管理',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='登录用户名', max_length=150, null=True, verbose_name='登录用户名')),
                ('ip', models.CharField(blank=True, help_text='登录ip', max_length=32, null=True, verbose_name='登录ip')),
                ('agent', models.TextField(blank=True, help_text='agent信息', null=True, verbose_name='agent信息')),
                ('browser', models.CharField(blank=True, help_text='浏览器名', max_length=200, null=True, verbose_name='浏览器名')),
                ('os', models.CharField(blank=True, help_text='操作系统', max_length=200, null=True, verbose_name='操作系统')),
                ('continent', models.CharField(blank=True, help_text='州', max_length=50, null=True, verbose_name='州')),
                ('country', models.CharField(blank=True, help_text='国家', max_length=50, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, help_text='省份', max_length=50, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, help_text='城市', max_length=50, null=True, verbose_name='城市')),
                ('district', models.CharField(blank=True, help_text='县区', max_length=50, null=True, verbose_name='县区')),
                ('isp', models.CharField(blank=True, help_text='运营商', max_length=50, null=True, verbose_name='运营商')),
                ('area_code', models.CharField(blank=True, help_text='区域代码', max_length=50, null=True, verbose_name='区域代码')),
                ('country_english', models.CharField(blank=True, help_text='英文全称', max_length=50, null=True, verbose_name='英文全称')),
                ('country_code', models.CharField(blank=True, help_text='简称', max_length=50, null=True, verbose_name='简称')),
                ('longitude', models.CharField(blank=True, help_text='经度', max_length=50, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, help_text='纬度', max_length=50, null=True, verbose_name='纬度')),
                ('login_type', models.IntegerField(choices=[(1, '普通登录'), (2, '普通扫码登录'), (3, '微信扫码登录'), (4, '飞书扫码登录'), (5, '钉钉扫码登录'), (6, '短信登录')], default=1, help_text='登录类型', verbose_name='登录类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志管理',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='岗位名称', max_length=64, verbose_name='岗位名称')),
                ('code', models.CharField(help_text='岗位编码', max_length=32, verbose_name='岗位编码')),
                ('sort', models.IntegerField(default=1, help_text='岗位顺序', verbose_name='岗位顺序')),
                ('status', models.IntegerField(choices=[(0, '离职'), (1, '在职')], default=1, help_text='岗位状态', verbose_name='岗位状态')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位管理',
                'ordering': ('sort',),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='department',
            name='key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='关联字符'),
        ),
        migrations.AddField(
            model_name='department',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='department',
            name='owner',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='department',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='显示排序'),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='部门状态'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='操作类型'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='操作详情'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='model_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='模型ID'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='模型名称'),
        ),
        migrations.AddField(
            model_name='role',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='是否为admin'),
        ),
        migrations.AddField(
            model_name='role',
            name='data_range',
            field=models.IntegerField(choices=[(0, '仅本人数据权限'), (1, '本部门及以下数据权限'), (2, '本部门数据权限'), (3, '全部数据权限'), (4, '自定数据权限')], default=0, help_text='数据权限范围', verbose_name='数据权限范围'),
        ),
        migrations.AddField(
            model_name='role',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True, verbose_name='权限字符'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='角色顺序'),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True, verbose_name='角色状态'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_no',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, help_text='性别', null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最后一次登录Token'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, help_text='姓名', max_length=40, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, '后台用户'), (1, '前台用户')], default=0, help_text='用户类型', null=True, verbose_name='用户类型'),
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='字典名称', max_length=100, null=True, verbose_name='字典名称')),
                ('value', models.CharField(blank=True, help_text='字典编号/实际值', max_length=200, null=True, verbose_name='字典编号')),
                ('type', models.IntegerField(choices=[(0, 'text'), (1, 'number'), (2, 'date'), (3, 'datetime'), (4, 'time'), (5, 'files'), (6, 'boolean'), (7, 'images')], default=0, help_text='数据值类型', verbose_name='数据值类型')),
                ('color', models.CharField(blank=True, help_text='颜色', max_length=20, null=True, verbose_name='颜色')),
                ('is_value', models.BooleanField(default=False, help_text='是否为value值,用来做具体值存放', verbose_name='是否为value值')),
                ('status', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=2000, null=True, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, help_text='父级', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sublist', to='dashboard.dictionary', verbose_name='父级')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典管理',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='菜单图标', max_length=64, null=True, verbose_name='菜单图标')),
                ('name', models.CharField(help_text='菜单名称', max_length=64, verbose_name='菜单名称')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('is_link', models.BooleanField(default=False, help_text='是否外链', verbose_name='是否外链')),
                ('is_catalog', models.BooleanField(default=False, help_text='是否目录', verbose_name='是否目录')),
                ('web_path', models.CharField(blank=True, help_text='路由地址', max_length=128, null=True, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, help_text='组件地址', max_length=128, null=True, verbose_name='组件地址')),
                ('component_name', models.CharField(blank=True, help_text='组件名称', max_length=50, null=True, verbose_name='组件名称')),
                ('status', models.BooleanField(blank=True, default=True, help_text='菜单状态', verbose_name='菜单状态')),
                ('cache', models.BooleanField(blank=True, default=False, help_text='是否页面缓存', verbose_name='是否页面缓存')),
                ('visible', models.BooleanField(blank=True, default=True, help_text='侧边栏中是否显示', verbose_name='侧边栏中是否显示')),
                ('parent', models.ForeignKey(blank=True, help_text='上级菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单管理',
                'ordering': ('sort',),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post',
            field=models.ForeignKey(blank=True, help_text='关联岗位', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.post', verbose_name='关联岗位'),
        ),
    ]
