# Generated by Django 5.2.5 on 2025-08-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_apiwhitelist_created_by_apiwhitelist_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=True, verbose_name='部门状态'),
        ),
    ]
