# Generated by Django 5.0.14 on 2025-09-05 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_menubutton_created_by_menubutton_deleted_at_and_more'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('task_name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('status', models.IntegerField(choices=[(0, '失败'), (1, '成功'), (2, '运行中')], default=2, verbose_name='执行状态')),
                ('result', models.TextField(blank=True, null=True, verbose_name='执行结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('args', models.TextField(blank=True, null=True, verbose_name='任务参数')),
                ('kwargs', models.TextField(blank=True, null=True, verbose_name='关键字参数')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask', verbose_name='定时任务')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '定时任务日志',
                'verbose_name_plural': '定时任务日志管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
