# Generated by Django 5.0.14 on 2025-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_message_usermessage_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('system', '系统通知'), ('task', '任务通知'), ('alert', '告警通知'), ('announcement', '公告')], default='system', max_length=20, verbose_name='消息类型'),
        ),
        migrations.AddField(
            model_name='message',
            name='priority',
            field=models.IntegerField(choices=[(0, '普通'), (1, '重要'), (2, '紧急')], default=0, verbose_name='优先级'),
        ),
    ]
