# Generated by Django 5.2.5 on 2025-09-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_message_message_type_message_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="task_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="任务ID",
            ),
        ),
    ]
