# Generated by Django 5.2.5 on 2025-09-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_tasklog_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="retry_count",
            field=models.IntegerField(default=0, verbose_name="重试次数"),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "失败"),
                    (1, "成功"),
                    (2, "运行中"),
                    (3, "已撤销"),
                    (4, "重试中"),
                ],
                default=2,
                verbose_name="执行状态",
            ),
        ),
    ]
