# Generated by Django 5.2.5 on 2025-09-09 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_tasklog_retry_count_alter_tasklog_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="文件名称", max_length=255, verbose_name="文件名称"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="文件路径",
                        upload_to="files/%Y/%m/%d",
                        verbose_name="文件路径",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="文件类型",
                        max_length=100,
                        null=True,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        help_text="文件大小(字节)", verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="文件描述",
                        null=True,
                        verbose_name="文件描述",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "文档"),
                            (1, "图片"),
                            (2, "视频"),
                            (3, "音频"),
                            (4, "压缩包"),
                            (5, "其他"),
                        ],
                        default=5,
                        help_text="文件分类",
                        verbose_name="文件分类",
                    ),
                ),
                (
                    "permission",
                    models.IntegerField(
                        choices=[(0, "私有"), (1, "部门可见"), (2, "公开")],
                        default=0,
                        help_text="访问权限",
                        verbose_name="访问权限",
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, help_text="下载次数", verbose_name="下载次数"
                    ),
                ),
                (
                    "last_download_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="最后下载时间",
                        null=True,
                        verbose_name="最后下载时间",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="关联部门",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.department",
                        verbose_name="关联部门",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        help_text="上传用户",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件",
                "verbose_name_plural": "文件管理",
                "ordering": ("-created_at",),
            },
        ),
    ]
