# Generated by Django 5.0.14 on 2025-09-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="progress",
            field=models.IntegerField(
                default=0, help_text="0-100之间的整数", verbose_name="任务进度(%)"
            ),
        ),
    ]
