# Generated by Django 5.0.14 on 2025-09-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_tasklog_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="receive_type",
            field=models.IntegerField(
                choices=[(0, "全部"), (1, "部门"), (2, "角色"), (3, "指定用户")],
                verbose_name="接收类型",
            ),
        ),
    ]
