# Generated by Django 5.0.14 on 2025-09-27 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_alter_message_receive_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dictionary",
            constraint=models.UniqueConstraint(
                fields=("parent", "value"), name="unique_dictionary_value_per_parent"
            ),
        ),
    ]
