# Generated by Django 5.0.14 on 2025-12-07 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_dictionary_unique_dictionary_value_per_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, '草稿'), (1, '已发布'), (2, '已撤回'), (3, '已过期')], default=1, verbose_name='消息状态'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='是否已处理'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.CreateModel(
            name='UserMessageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('enable_system_notify', models.BooleanField(default=True, verbose_name='启用系统通知')),
                ('system_notify_in_app', models.BooleanField(default=True, verbose_name='系统通知-应用内')),
                ('system_notify_email', models.BooleanField(default=False, verbose_name='系统通知-邮件')),
                ('enable_task_notify', models.BooleanField(default=True, verbose_name='启用任务通知')),
                ('task_notify_in_app', models.BooleanField(default=True, verbose_name='任务通知-应用内')),
                ('task_notify_email', models.BooleanField(default=True, verbose_name='任务通知-邮件')),
                ('enable_alert_notify', models.BooleanField(default=True, verbose_name='启用告警通知')),
                ('alert_notify_in_app', models.BooleanField(default=True, verbose_name='告警通知-应用内')),
                ('alert_notify_email', models.BooleanField(default=True, verbose_name='告警通知-邮件')),
                ('alert_notify_sms', models.BooleanField(default=False, verbose_name='告警通知-短信')),
                ('enable_announcement_notify', models.BooleanField(default=True, verbose_name='启用公告通知')),
                ('announcement_notify_in_app', models.BooleanField(default=True, verbose_name='公告通知-应用内')),
                ('announcement_notify_email', models.BooleanField(default=True, verbose_name='公告通知-邮件')),
                ('email_notify_frequency', models.IntegerField(choices=[(0, '即时'), (1, '每日汇总'), (2, '每周汇总')], default=0, verbose_name='邮件通知频率')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_settings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户消息接收设置',
                'verbose_name_plural': '用户消息接收设置管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
