# Generated by Django 5.0.14 on 2026-06-16 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_add_tenant_workflow_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='usermessagesettings',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='apiwhitelist',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='button',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='menubutton',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(help_text='唯一标识，用于数据隔离', max_length=50, unique=True, verbose_name='租户编码'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, help_text='用于子域名访问', max_length=255, null=True, unique=True, verbose_name='租户域名'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_storage',
            field=models.BigIntegerField(default=10737418240, help_text='默认10GB', verbose_name='最大存储空间(字节)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_users',
            field=models.IntegerField(default=100, help_text='0表示不限制', verbose_name='最大用户数'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='为空表示系统级数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tenant', to='dashboard.tenant', verbose_name='所属租户'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='code',
            field=models.CharField(help_text='唯一标识', max_length=50, unique=True, verbose_name='流程编码'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='business_key',
            field=models.CharField(blank=True, help_text='关联业务数据ID', max_length=100, null=True, verbose_name='业务主键'),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='candidate_roles',
            field=models.JSONField(default=list, help_text='角色ID列表', verbose_name='候选角色列表'),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='candidate_users',
            field=models.JSONField(default=list, help_text='用户ID列表', verbose_name='候选用户列表'),
        ),
    ]
