# Generated by Django 5.0.14 on 2026-06-16 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_tasklog_tenant_usermessagesettings_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='last_access_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['code', 'status'], name='dashboard_t_code_b2a2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status', '-created_at'], name='dashboard_t_status_9acb36_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['domain'], name='dashboard_t_domain_a29aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'is_active'], name='dashboard_t_tenant__02d703_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['user', 'is_active'], name='dashboard_t_user_id_3889a3_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'role'], name='dashboard_t_tenant__b2f7f9_idx'),
        ),
    ]
