# Generated by Django 5.0.14 on 2026-06-16 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_tenantuser_last_access_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['created_by'], name='dashboard_t_created_75e2b0_idx'),
        ),
    ]
